In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

In [2]:
data_train = pd.read_csv('data/train.csv')
data_train

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [3]:
data_train.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [4]:
target = data_train['Survived']

data = data_train[['Pclass', 'Sex', 'SibSp', 'Parch', 'Fare']]
data['Sex'][data['Sex'] == 'male'] = 0
data['Sex'][data['Sex'] == 'female'] = 1
# data['Age'][data['Age'].isna()] = data['Age'].mean(skipna=True)

data = data.to_numpy(dtype=float)
data = (data - data.mean(axis=0)) / data.std(axis=0)

C:\Users\valeryi\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
C:\Users\valeryi\Anaconda3\lib\site-packages\pandas\core\generic.py:8765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._update_inplace(new_data)
C:\Users\valeryi\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """


In [5]:
model = LogisticRegression(C=1)

In [6]:
model = LogisticRegression(C=1)
cross_val_score(model, data, target, cv=5)

array([0.80446927, 0.80337079, 0.78089888, 0.76966292, 0.81460674])

In [7]:
cross_val_score?

In [8]:
data

array([[ 0.82737724, -0.73769513,  0.43279337, -0.47367361, -0.50244517],
       [-1.56610693,  1.35557354,  0.43279337, -0.47367361,  0.78684529],
       [ 0.82737724,  1.35557354, -0.4745452 , -0.47367361, -0.48885426],
       ...,
       [ 0.82737724,  1.35557354,  0.43279337,  2.00893337, -0.17626324],
       [-1.56610693, -0.73769513, -0.4745452 , -0.47367361, -0.04438104],
       [ 0.82737724, -0.73769513, -0.4745452 , -0.47367361, -0.49237783]])

In [18]:
data_test = pd.read_csv('data/test.csv')
data_test.isna().sum()
TEST = data_test[['Pclass', 'Sex', 'SibSp', 'Parch', 'Fare']]
TEST['Fare'][TEST['Fare'].isna()] = data_train['Fare'].mean()

TEST['Sex'][TEST['Sex'] == 'male'] = 0
TEST['Sex'][TEST['Sex'] == 'female'] = 1

TEST = TEST.to_numpy(dtype=float)
TEST = (TEST - TEST.mean(axis=0)) / TEST.std(axis=0)

C:\Users\valeryi\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
C:\Users\valeryi\Anaconda3\lib\site-packages\pandas\core\generic.py:8765: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._update_inplace(new_data)
C:\Users\valeryi\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
C:\Users\valeryi\

In [21]:
model = LogisticRegression()
model.fit(data, target)
print(cross_val_score(model, data, target, cv=5))
y_pred = model.predict(TEST)

ans = pd.DataFrame({'PassengerId':data_test['PassengerId'], 'Survived': y_pred}).set_index('PassengerId')
ans.to_csv('result_2.csv')

[0.80446927 0.80337079 0.78089888 0.76966292 0.81460674]


In [12]:
data

array([[ 0.82737724, -0.73769513,  0.43279337, -0.47367361, -0.50244517],
       [-1.56610693,  1.35557354,  0.43279337, -0.47367361,  0.78684529],
       [ 0.82737724,  1.35557354, -0.4745452 , -0.47367361, -0.48885426],
       ...,
       [ 0.82737724,  1.35557354,  0.43279337,  2.00893337, -0.17626324],
       [-1.56610693, -0.73769513, -0.4745452 , -0.47367361, -0.04438104],
       [ 0.82737724, -0.73769513, -0.4745452 , -0.47367361, -0.49237783]])

In [11]:
ans

Survived
PassengerId          
892                 0
893                 0
894                 0
895                 0
896                 1
...               ...
1305                0
1306                1
1307                0
1308                0
1309                1

[418 rows x 1 columns]